final Map<String, Map<String, String>> localizedValues =
    <String, Map<String, String>>{
  'de': <String, String>{
    'addTransaction': 'In Transaktion',
    'currencyOnLeft': 'Währung auf links',
    'defaultCurrency': 'Standardwährung',
    'enterDefaultCurrency': 'Geben Sie Standardwährung',
    'ledgerFile': 'Ledger-Datei',
    'settings': 'die Einstellungen',
    'submit': 'einreichen',
  },
  'en': <String, String>{
    'addTransaction': 'Add transaction',
    'currencyOnLeft': 'Currency on left',
    'defaultCurrency': 'Default Currency',
    'enterDefaultCurrency': 'Enter default currency',
    'ledgerFile': 'Ledger file',
    'settings': 'Settings',
    'submit': 'Submit',
  },
  'es': <String, String>{
    'addTransaction': 'Añadir transacción',
    'currencyOnLeft': 'Moneda a la izquierda',
    'defaultCurrency': 'Moneda por defecto',
    'enterDefaultCurrency': 'Introduzca la moneda por defecto',
    'ledgerFile': 'Archivo contable',
    'settings': 'Ajustes',
    'submit': 'Enviar',
  },
  'fil': <String, String>{
    'addTransaction': 'Magdagdag ng transaksyon',
    'currencyOnLeft': 'Pera sa kaliwa',
    'defaultCurrency': 'default Pera',
    'enterDefaultCurrency': 'Ipasok ang default ng pera',
    'ledgerFile': 'ledger file',
    'settings': 'Mga Setting',
    'submit': 'Ipasa',
  },
  'fr': <String, String>{
    'addTransaction': 'Ajouter transaction',
    'currencyOnLeft': 'Monnaie à gauche',
    'defaultCurrency': 'devise par défaut',
    'enterDefaultCurrency': 'Entrer la devise par défaut',
    'ledgerFile': 'fichier Ledger',
    'settings': 'Paramètres',
    'submit': 'Soumettre',
  },
  'hi': <String, String>{
    'addTransaction': 'लेन-देन में जोड़ें',
    'currencyOnLeft': 'बाईं तरफ मुद्रा',
    'defaultCurrency': 'डिफ़ॉल्ट मुद्रा',
    'enterDefaultCurrency': 'डिफ़ॉल्ट मुद्रा दर्ज करें',
    'ledgerFile': 'लेजर फ़ाइल',
    'settings': 'समायोजन',
    'submit': 'प्रस्तुत',
  },
  'in': <String, String>{
    'addTransaction': 'menambahkan transaksi',
    'currencyOnLeft': 'Mata uang di sebelah kiri',
    'defaultCurrency': 'Currency default',
    'enterDefaultCurrency': 'Masukkan mata uang default',
    'ledgerFile': 'File Ledger',
    'settings': 'pengaturan',
    'submit': 'Kirimkan',
  },
  'it': <String, String>{
    'addTransaction': 'Aggiungere transazione',
    'currencyOnLeft': 'Valuta a sinistra',
    'defaultCurrency': 'valuta di default',
    'enterDefaultCurrency': 'Inserire la valuta di default',
    'ledgerFile': 'file di Ledger',
    'settings': 'impostazioni',
    'submit': 'Sottoscrivi',
  },
  'ja': <String, String>{
    'addTransaction': 'トランザクションを追加',
    'currencyOnLeft': '左側の通貨',
    'defaultCurrency': 'デフォルト通貨',
    'enterDefaultCurrency': 'デフォルトの通貨を入力します。',
    'ledgerFile': '元帳ファイル',
    'settings': '設定',
    'submit': '提出する',
  },
  'pt': <String, String>{
    'addTransaction': 'Adicionar transação',
    'currencyOnLeft': 'Moeda à esquerda',
    'defaultCurrency': 'Moeda padrão',
    'enterDefaultCurrency': 'Digite moeda predefinida',
    'ledgerFile': 'Arquivo de contabilidade',
    'settings': 'Definições',
    'submit': 'Enviar',
  },
  'ru': <String, String>{
    'addTransaction': 'Добавить транзакцию',
    'currencyOnLeft': 'Валюта слева',
    'defaultCurrency': 'Валюта по-умолчанию',
    'enterDefaultCurrency': 'Введите валюту по-умолчанию',
    'ledgerFile': 'Файл бухгалтерской книги',
    'settings': 'Настройки',
    'submit': 'Принять',
  },
  'th': <String, String>{
    'addTransaction': 'เพิ่มการจำหน่าย',
    'currencyOnLeft': 'สกุลเงินบนด้านซ้าย',
    'defaultCurrency': 'ค่าสกุลเงินเริ่มต้น',
    'enterDefaultCurrency': 'ใส่สกุลเงินเริ่มต้น',
    'ledgerFile': 'ไฟล์แฟ้มบัญชี',
    'settings': 'การตั้งค่า',
    'submit': 'เสนอ',
  },
  'zh': <String, String>{
    'addTransaction': '添加交易',
    'currencyOnLeft': '货币左',
    'defaultCurrency': '默认货币',
    'enterDefaultCurrency': '输入默认货币',
    'ledgerFile': '总帐文件',
    'settings': '设置',
    'submit': '提交',
  },
};
