name: cone_cli
description: A sample command-line application for cone.
version: 0.1.0
homepage: https://github.com/bradyt/cone/tree/master/cone_lib/example/
author: Brady Trainor <mail@bradyt.net>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  cone_lib:
    path: ..

executables:
  cone: main

dev_dependencies:
  build_runner:
  build_version:
